class Map:
    Locators= dict(signinbtn='//a[@class="login"]',
                   enteremail='//input[@id="email_create"]',
                   createbutton='//button[@id="SubmitCreate"]',
                   radiobtn='(//input[@type="radio"])[1]',
                   firstname='//input[@id="customer_firstname"]',
                   lastname='//input[@id="customer_lastname"]',
                   passwordField='//input[@id="passwd"]', 
                   selectdate='//select[@id="days"]/option[@value="8"]',
                   selectmonth='//select[@id="months"]/option[@value="6"]', 
                   selectyear='//select[@id="years"]/option[@value="1994"]',
                   addressinfo='//input[@id="address1"]',
                   addresscity='//input[@id="city"]',
                   addressstate='//select[@id="id_state"]/option[@value="1"]',
                   addresszip='//input[@id="postcode"]',
                   addressphnum='//input[@id="phone_mobile"]',
                   addressalias='//input[@id="alias"]',
                   addressregister='//button[@id="submitAccount"]',
                   usertext='//a[@title="View my customer account"]')